<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <ProjectReference Include="../LightBulb.Core/LightBulb.Core.csproj" />
    <ProjectReference Include="../LightBulb.PlatformInterop/LightBulb.PlatformInterop.csproj" />
  </ItemGroup>
</Project>
