<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="LightBulb.Core.Tests" />
    <InternalsVisibleTo Include="Candlelight.Migration" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <PackageReference Include="PowerKit" />
  </ItemGroup>
</Project>
