<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.2.7</Version>
    <Win32Resource>obj/Accessibility.res</Win32Resource>
    <DefineConstants>$(DefineConstants);CANDLELIGHT_ENGINE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <Compile Include="../LightBulb.PlatformInterop/MonitorIdentity.cs" Link="MonitorIdentity.cs" />
    <InternalsVisibleTo Include="LightBulb.Core.Tests" />
    <InternalsVisibleTo Include="Candlelight.Next" />
  </ItemGroup>
  <Target Name="CreateAccessibilityResources" BeforeTargets="CoreCompile">
    <Exec Command="powershell.exe -NoProfile -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)/../scripts/write-accessibility-resource.ps1&quot; -OutputPath &quot;$(MSBuildProjectDirectory)/$(Win32Resource)&quot;" />
  </Target>
</Project>
